apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/pm/server/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  PORT: '80'
  STEP_TIME: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: service-svc
  labels:
    app: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverdeployment
  labels:
    app: server
spec:
  replicas: 1
  template:
    metadata:
      name: serverPod
      labels:
        app: server
    spec:
      containers:
        - name: serverimage
          image: preethamhd23/socketserver:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          volumeMounts:
            - mountPath: '/var/pm/server/'
              name: servervol

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: PORT
            - name: STEP_TIME
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: STEP_TIME

          command: ['./var/lib/server']
          args: ['$(PORT)', '$(STEP_TIME)']

      volumes:
        - name: servervol
          persistentVolumeClaim:
            claimName: server-pvc

  selector:
    matchLabels:
      app: server
